'use client';

import { useEffect, useState } from 'react';
import { getActiveSession } from '@/lib/auth/session';
import { createMember, disableMember, listMembers } from '@/lib/data/members';
import type { AppProfile, AppRole } from '@/lib/types';

const ROLE_LABEL: Record<AppRole, string> = { admin: '管理员', leader: '项目负责人', consultant: '猎头顾问', operator: '数据运营' };

export default function MembersPage() {
  const [members, setMembers] = useState<AppProfile[]>([]); const [allowed, setAllowed] = useState<boolean | null>(null); const [error, setError] = useState('');
  const [form, setForm] = useState({ username: '', displayName: '', department: '', role: 'consultant' as AppRole, password: '', confirm: '' });
  async function refresh() { const data = await listMembers(); setMembers(data as AppProfile[]); }
  useEffect(() => { getActiveSession().then((active) => { const ok = active?.profile.role === 'admin'; setAllowed(ok); if (ok) void refresh(); }); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if (form.password !== form.confirm) { setError('两次输入的密码不一致'); return; } try { await createMember(form); setForm((value) => ({ ...value, username: '', displayName: '', department: '' })); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '创建失败'); } finally { setForm((value) => ({ ...value, password: '', confirm: '' })); } }
  async function disable(member: AppProfile) { if (!window.confirm(`确认停用成员“${member.display_name}”吗？`)) return; try { await disableMember(member.id); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '停用失败'); } }
  if (allowed === null) return <div className="text-warm-400">加载中…</div>; if (!allowed) return <div className="text-warm-500">仅管理员可以访问成员管理。</div>;
  return <div><header className="mb-6"><h1 className="text-xl font-semibold text-warm-600">成员管理</h1><p className="mt-1 text-sm text-warm-400">创建内部账号与停用成员</p></header><div className="grid grid-cols-[360px_1fr] gap-5"><form onSubmit={submit} className="surface p-5"><h2 className="font-medium text-warm-600">新建成员</h2>{[['username','用户名'],['displayName','姓名'],['department','部门']].map(([key,label]) => <label key={key} className="mt-3 block text-xs text-warm-500">{label}<input required={key !== 'department'} value={form[key as 'username']} onChange={(e) => setForm((value) => ({ ...value, [key]: e.target.value }))} className="mt-1 w-full rounded-lg border border-warm-200 px-3 py-2 text-sm" /></label>)}<label className="mt-3 block text-xs text-warm-500">角色<select value={form.role} onChange={(e) => setForm((value) => ({ ...value, role: e.target.value as AppRole }))} className="mt-1 w-full rounded-lg border p-2 text-sm">{Object.entries(ROLE_LABEL).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="mt-3 block text-xs text-warm-500">密码（至少 12 位）<input type="password" minLength={12} required value={form.password} onChange={(e) => setForm((value) => ({ ...value, password: e.target.value }))} className="mt-1 w-full rounded-lg border p-2 text-sm" /></label><label className="mt-3 block text-xs text-warm-500">再次输入密码<input type="password" minLength={12} required value={form.confirm} onChange={(e) => setForm((value) => ({ ...value, confirm: e.target.value }))} className="mt-1 w-full rounded-lg border p-2 text-sm" /></label>{error && <div className="mt-3 text-sm text-red-600">{error}</div>}<button className="mt-4 w-full rounded-lg bg-forest-600 py-2 text-sm text-white">创建成员</button></form><div className="surface overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b bg-warm-50">{['姓名','部门','角色','状态','操作'].map((label) => <th key={label} className="px-4 py-3 text-left font-medium text-warm-500">{label}</th>)}</tr></thead><tbody>{members.map((member) => <tr key={member.id} className="border-b border-warm-100"><td className="px-4 py-3">{member.display_name}</td><td className="px-4 py-3">{member.department || '—'}</td><td className="px-4 py-3">{ROLE_LABEL[member.role]}</td><td className="px-4 py-3">{member.status === 'active' ? '启用' : '已停用'}</td><td className="px-4 py-3">{member.status === 'active' && <button onClick={() => void disable(member)} className="text-xs text-red-600">停用</button>}</td></tr>)}</tbody></table></div></div></div>;
}
